name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest

    steps:

    # Step 1 — Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2 — Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3 — Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn joblib huggingface_hub datasets

    # Step 4 — Run Model Training Script
    - name: Train and Evaluate Model
      run: |
        python model_building/model_build_eval.py
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}

    # Step 5 — Deploy Streamlit App to Hugging Face Space
    - name: Deploy to Hugging Face Space
      run: |
        python model_building/deploy.py
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
